# .travis.yml
language: java
jdk:
  - openjdk8
services:
  - docker

before_install:
  - docker build -t userbox/webapp -f Dockerfile .

script:
  - ./gradlew clean build --parallel
  - ./gradlew test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: simple-web-calculus
  on:
    repo: merxyz/webapp
  skip_cleanup: true


